import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "@/components/ui/Head";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="container">
        <div className="sticky top-0 z-50">
          <Head />
         <NavBar />
        </div>
        
        {children}
      </body>
    </html>
  );
}
